#!/bin/bash

cd ~/GITHUB/main

clear

# git checkout master
# git pull
# git checkout -b TEMPBRANCH

git checkout master
git pull

count=`git branch -a | grep TEMPBRANCH| grep -v remotes/origin | wc -l `
  # Force it to a number. 
let count=$count+0


#echo "count $count"

if [ $count -gt 0 ] ; then
#  git branch -av | grep TEMPBRANCH| grep -v remotes/origin

  echo "Branch TEMPBRANCH aleady exists, trying to get into it"
  echo "You might have to delete it if we can't get in."
  echo " try: git checkout master"
  echo "      git branch -d TEMPBRANCH"
  echo "      git branch --delete --remotes origin/TEMPBRANCH"

  echo " "
  echo "Trying to get in..... you might want to run: git status"
  git checkout TEMPBRANCH
  echo "You are in the current branch:"
  git branch
  exit
fi

echo "Making branch TEMPBRANCH"
git checkout -b TEMPBRANCH

echo "You are in the current branch:"
git branch
