#!/bin/bash

# Must have an stuff defined.

mkdir -p ~/tmp

COPY=~/GITHUB_COPY/main
LIVE=~/github/main
TMPDIR=~/tmp

if ! [ -d "$COPY" ] ;
  then
    echo "copy directory doesn't exist"
    exit
fi	

echo "Updating copy of github."
echo "Change master in checkout and push commands if main branch is not master."

cd $COPY
echo "Branches, first one should be main branch."
git branch


echo ""
git checkout master
status=$?
if  ! [ $status -eq 0 ] ; then
   echo "Could not update copy of it, wrong name for main branch?"
   exit
fi

git pull
status=$?
if  ! [ $status -eq 0 ] ; then
   echo "Could not pull git, aborting."
   exit
fi

echo "Syncing changes to GITHUB"
cd $LIVE

# checks if we using master or not defined
# aborts if we are in another
status=""
b=`git branch --show-current`
if [ $? == 0 ];
  then
	git checkout master
	status="ok";
fi
if [ $status != "ok" ];
  then
    if [ $b == "master" ];
      then
        status = "ok";
    fi
fi

if [ $status == "ok" ]; then echo "git status good"; fi

# We just want the list of file compare to COPY, filter out things we don't want. 
rsync -nra --out-format="%n"  $LIVE/ $COPY/ --size-only  --exclude=".git" > $TMPDIR/gittmp.txt
egrep -v "^./" $TMPDIR/gittmp.txt | egrep -v "~$" |egrep -v "/$"  > $TMPDIR/gitdiff.txt

# Force adding each file
# This can result in some errors if done twice, but if later committed and pushed its okay. 
echo "adding files"
while IFS= read -r line; do
    echo "adding : $line"
    git add -v "$line"
done < $TMPDIR/gitdiff.txt

# Commit and sync to remote master
# committing remotely. 
git commit -m "auto "
git push origin -u master
